package ink

import (
	"crypto/ed25519"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"os"
	"strings"
	"testing"
)

// goldenPath is the producer corpus emitted by the TypeScript reference signer,
// regenerated by scripts/gen-body-signature-vectors.ts.
const goldenPath = "testdata/body-signature-producer.json"

type producerGoldens struct {
	SignerPrivateKeySeedHex string `json:"signerPrivateKeySeedHex"`
	SignerPublicKeyHex      string `json:"signerPublicKeyHex"`
	Cases                   []struct {
		Description string         `json:"description"`
		Body        map[string]any `json:"body"`
		Signature   string         `json:"signature"`
	} `json:"cases"`
}

func loadProducerGoldens(t *testing.T) (producerGoldens, ed25519.PrivateKey, []byte) {
	t.Helper()
	raw, err := os.ReadFile(goldenPath)
	if err != nil {
		t.Fatalf("read %s: %v", goldenPath, err)
	}
	var g producerGoldens
	if err := json.Unmarshal(raw, &g); err != nil {
		t.Fatalf("parse %s: %v", goldenPath, err)
	}
	if len(g.Cases) == 0 {
		t.Fatalf("%s: no cases", goldenPath)
	}
	seed, err := hex.DecodeString(g.SignerPrivateKeySeedHex)
	if err != nil || len(seed) != ed25519.SeedSize {
		t.Fatalf("%s: bad signer seed", goldenPath)
	}
	pub, err := hex.DecodeString(g.SignerPublicKeyHex)
	if err != nil || len(pub) != ed25519.PublicKeySize {
		t.Fatalf("%s: bad signer public key", goldenPath)
	}
	priv := ed25519.NewKeyFromSeed(seed)
	if !ed25519.PublicKey(pub).Equal(priv.Public()) {
		t.Fatalf("%s: seed does not derive the declared public key", goldenPath)
	}
	return g, priv, pub
}

// TestSignInkBodyMatchesReferenceGoldens is the cross-implementation proof for
// the body signature producer: for every golden body, the Go signer MUST emit
// the exact base64url signature the TypeScript reference emitted. Byte equality
// can only hold if the canonicalization, the version-keyed domain selection and
// the `signature`-stripping all agree, so this is stronger than a Go-only round
// trip.
func TestSignInkBodyMatchesReferenceGoldens(t *testing.T) {
	g, priv, _ := loadProducerGoldens(t)
	for _, c := range g.Cases {
		t.Run(c.Description, func(t *testing.T) {
			got, err := SignInkBody(c.Body, priv)
			if err != nil {
				t.Fatalf("SignInkBody: %v", err)
			}
			if got != c.Signature {
				t.Errorf("signature mismatch\n got %s\nwant %s", got, c.Signature)
			}
		})
	}
}

// TestSignInkBodyGoldensCoverBothDomains guards the corpus itself: a golden set
// that drifted to one protocol version would still pass the byte comparison
// above while proving nothing about domain selection.
func TestSignInkBodyGoldensCoverBothDomains(t *testing.T) {
	g, _, _ := loadProducerGoldens(t)
	var legacy, v02 int
	for _, c := range g.Cases {
		if bodySignatureDomain(c.Body) == v02BodySignDomain {
			v02++
		} else {
			legacy++
		}
	}
	if legacy == 0 || v02 == 0 {
		t.Fatalf("goldens must cover both domains: legacy=%d ink/0.2=%d", legacy, v02)
	}
}

// TestSignInkBodyRoundTrip signs a body with the Go producer and verifies the
// signature against the domain-prefixed canonical bytes the Go canonicalizer
// rebuilds, so the producer and the package's own canonicalization agree without
// consulting the goldens.
func TestSignInkBodyRoundTrip(t *testing.T) {
	_, priv, pub := loadProducerGoldens(t)
	body := map[string]any{
		"protocol": "ink/0.2",
		"id":       "01HROUNDTRIP0000000000000000",
		"from":     "did:key:zAlice",
		"to":       "did:key:zBob",
		"intent":   "ping",
		"payload":  map[string]any{"note": "hello"},
	}
	sig, err := SignInkBody(body, priv)
	if err != nil {
		t.Fatalf("SignInkBody: %v", err)
	}
	canonical, err := JCSCanonicalize(body)
	if err != nil {
		t.Fatalf("JCSCanonicalize: %v", err)
	}
	sigBytes, err := base64.RawURLEncoding.DecodeString(sig)
	if err != nil {
		t.Fatalf("decode signature: %v", err)
	}
	if !ed25519.Verify(ed25519.PublicKey(pub), []byte(v02BodySignDomain+canonical), sigBytes) {
		t.Error("Go-produced body signature did not verify over the Go canonical bytes")
	}
	// The legacy domain must NOT verify the same signature: a verifier that tried
	// both domains would accept a cross-version replay.
	if ed25519.Verify(ed25519.PublicKey(pub), []byte(legacyBodySignDomain+canonical), sigBytes) {
		t.Error("an ink/0.2 signature verified under the legacy domain")
	}
}

// TestSignInkBodyStripsSignature pins that an already-signed body re-signs to the
// same value as its unsigned form: the `signature` member is removed before
// canonicalization, so a re-sign is idempotent rather than self-referential.
func TestSignInkBodyStripsSignature(t *testing.T) {
	_, priv, _ := loadProducerGoldens(t)
	body := map[string]any{"protocol": "ink/0.1", "intent": "ping"}
	first, err := SignInkBody(body, priv)
	if err != nil {
		t.Fatalf("SignInkBody: %v", err)
	}
	signed := map[string]any{"protocol": "ink/0.1", "intent": "ping", "signature": first}
	second, err := SignInkBody(signed, priv)
	if err != nil {
		t.Fatalf("SignInkBody on a signed body: %v", err)
	}
	if first != second {
		t.Errorf("re-signing a signed body changed the signature: %s vs %s", first, second)
	}
	// The caller's map must not be mutated by the strip.
	if _, ok := signed["signature"]; !ok {
		t.Error("SignInkBody mutated the caller's body")
	}
}

// TestSignInkBodyRejectsBadInput pins the producer's input guards. Each mirrors a
// reject the reference signMessage makes, so the Go signer cannot mint a
// signature over a body the reference would refuse to sign.
func TestSignInkBodyRejectsBadInput(t *testing.T) {
	_, priv, _ := loadProducerGoldens(t)
	if _, err := SignInkBody(nil, priv); err == nil {
		t.Error("nil body accepted")
	}
	if _, err := SignInkBody(map[string]any{"a": 1}, ed25519.PrivateKey(make([]byte, 31))); err == nil {
		t.Error("short private key accepted")
	}
	// A non-JCS-safe number: the reference rejects it in isWithinBounds before
	// canonicalizing.
	if _, err := SignInkBody(map[string]any{"n": 1.5}, priv); err == nil {
		t.Error("fractional number accepted")
	}
	if _, err := SignInkBody(map[string]any{"n": float64(int64(1) << 60)}, priv); err == nil {
		t.Error("out-of-range number accepted")
	}
	// Invalid UTF-8 in a string is the Go analogue of the reference's unpaired
	// UTF-16 surrogate: it does not canonicalize to portable bytes.
	if _, err := SignInkBody(map[string]any{"s": string([]byte{0xff, 0xfe})}, priv); err == nil {
		t.Error("invalid UTF-8 string accepted")
	}
	// A non-JSON in-memory value cannot be canonicalized portably.
	type notJSON struct{ A int }
	if _, err := SignInkBody(map[string]any{"x": notJSON{A: 1}}, priv); err == nil {
		t.Error("struct-valued member accepted")
	}
	// Over-deep bodies are refused before the recursive canonicalization runs.
	deep := map[string]any{}
	cur := deep
	for i := 0; i < 64; i++ {
		next := map[string]any{}
		cur["n"] = next
		cur = next
	}
	if _, err := SignInkBody(deep, priv); err == nil {
		t.Error("over-deep body accepted")
	}
}

// TestJCSCanonicalizeExportedSurface pins the exported canonicalizer against the
// RFC 8785 rules a second implementation needs to assemble a signed body: member
// ordering by UTF-16 code unit, minimal escaping and the safe-integer number
// profile.
func TestJCSCanonicalizeExportedSurface(t *testing.T) {
	got, err := JCSCanonicalize(map[string]any{
		"z": 1,
		"a": []any{true, nil, "x"},
		"é": "e",
	})
	if err != nil {
		t.Fatalf("JCSCanonicalize: %v", err)
	}
	const want = `{"a":[true,null,"x"],"z":1,"é":"e"}`
	if got != want {
		t.Errorf("canonical = %s, want %s", got, want)
	}

	// Ordering by UTF-16 code unit is not ordering by UTF-8 bytes. U+1F511 is
	// the surrogate pair D83D DD11, so it sorts BEFORE the single code unit
	// U+FF21; its UTF-8 encoding (F0 9F 94 91) sorts AFTER U+FF21's (EF BC A1).
	// A canonicalizer that sorted members by raw bytes would emit the two
	// members the other way round, so this pair is what makes the ordering
	// producer golden discriminating rather than merely decorative.
	gotOrder, err := JCSCanonicalize(map[string]any{
		"\U0001F511": 1,
		"Ａ":          2,
		"é":          3,
		"z":          4,
		"a":          5,
		"Z":          6,
	})
	if err != nil {
		t.Fatalf("JCSCanonicalize: %v", err)
	}
	const wantOrder = `{"Z":6,"a":5,"z":4,"é":3,"🔑":1,"Ａ":2}`
	if gotOrder != wantOrder {
		t.Errorf("canonical member order = %s, want %s", gotOrder, wantOrder)
	}
	if strings.Index(gotOrder, "\U0001F511") > strings.Index(gotOrder, "Ａ") {
		t.Error("U+1F511 must sort before U+FF21 under UTF-16 code-unit ordering")
	}
	if _, err := JCSCanonicalize(map[string]any{"n": 0.5}); err == nil {
		t.Error("fractional number accepted")
	}
	if _, err := JCSCanonicalize(map[string]any{"s": string([]byte{0xff})}); err == nil {
		t.Error("invalid UTF-8 accepted")
	}
	// An oversized canonical form is refused, mirroring the reference cap.
	if _, err := JCSCanonicalize(map[string]any{"s": strings.Repeat("x", maxCanonicalBodyBytes+1)}); err == nil {
		t.Error("oversized canonical output accepted")
	}
}
